services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb

    volumes:
      - postgres5-data:/var/lib/postgresql/data
    ports:
      - 54320:5432

volumes:
  postgres5-data:

